DROP TABLE IF EXISTS EventType;
CREATE TABLE EventType (TypeID int PRIMARY KEY, Name text);
INSERT INTO EventType VALUES
(1, 'pass'),
(2, 'offside pass'),
(4, 'foul'),
(6, 'corner awarded'),
(8, 'interception'),
(9, 'turnover'),
(10, 'save'),
(11, 'claim'),
(12, 'clearance'),
(13, 'miss'),
(14, 'post'),
(15, 'attempt saved'),
(16, 'goal'),
(17, 'card'),
(18, 'player off'),
(19, 'player on'),
(24, 'condition change'),
(26, 'unknown'),
(41, 'punch'),
(42, 'good skill'),
(45, 'challenge'),
(47, 'rescinded card'),
(49, 'ball recovery'),
(51, 'error'),
(52, 'keeper pick-up'),
(53, 'cross not claimed'),
(55, 'offside provoked'),
(56, 'shield ball opp'),
(57, 'foul throw in'),
(58, 'penalty faced'),
(59, 'keeper sweeper'),
(60, 'chance missed'),
(61, 'ball touch');